# Generated by Django 5.2.5 on 2025-08-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryHello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
